<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>cz.cuni.mff.vojtusr</groupId>
    <artifactId>InformalMDD</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>EclipseIDE</module>
        <module>IntelliJ</module>
        <module>umlet</module>
        <module>InformalMDD-core</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Shared dependencies can be managed here -->
        </dependencies>
    </dependencyManagement>
</project>
