<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cz.cuni.mff</groupId>
    <artifactId>UMLift</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <licenses>
        <license>
            <name>GPL-3.0-or-later</name>
            <url>https://www.gnu.org/licenses/gpl-3.0.html</url>
        </license>
    </licenses>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>UMLift-core</module>
        <module>UMLift-maven-plugin</module>
        <module>UMLift-Standalone</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.4.1</version>
                    <executions>
                        <execution>
                            <id>enforce-maven</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <requireMavenVersion>
                                        <version>3.2.5</version>
                                    </requireMavenVersion>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>

                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.4</version>
                    <inherited>false</inherited>
                    <executions>
                        <execution>
                            <id>install-pom-parent</id>
                            <goals>
                                <goal>install-file</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <groupId>com.umlet</groupId>
                                <artifactId>umlet-parent</artifactId>
                                <version>15.1</version>
                                <packaging>pom</packaging>
                                <file>dependencies/umlet-parent/umlet-parent-15.1.pom</file>
                                <generatePom>false</generatePom>
                            </configuration>
                        </execution>
                        <execution>
                            <id>install-jar-standalone</id>
                            <goals>
                                <goal>install-file</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <groupId>com.umlet</groupId>
                                <artifactId>umlet-standalone</artifactId>
                                <version>15.1</version>
                                <packaging>jar</packaging>
                                <file>dependencies/umlet-standalone/umlet-standalone-15.1.jar</file>
                                <generatePom>false</generatePom>
                                <pomFile>dependencies/umlet-standalone/umlet-standalone-15.1.pom</pomFile>
                            </configuration>
                        </execution>
                        <execution>
                            <id>install-jar-swing</id>
                            <goals>
                                <goal>install-file</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <groupId>com.umlet</groupId>
                                <artifactId>umlet-swing</artifactId>
                                <version>15.1</version>
                                <packaging>jar</packaging>
                                <file>dependencies/umlet-swing/umlet-swing-15.1.jar</file>
                                <generatePom>false</generatePom>
                                <pomFile>dependencies/umlet-swing/umlet-swing-15.1.pom</pomFile>
                            </configuration>
                        </execution>
                        <execution>
                            <id>install-jar-elements</id>
                            <goals>
                                <goal>install-file</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <groupId>com.umlet</groupId>
                                <artifactId>umlet-elements</artifactId>
                                <version>15.1</version>
                                <packaging>jar</packaging>
                                <file>dependencies/umlet-elements/umlet-elements-15.1.jar</file>
                                <generatePom>false</generatePom>
                                <pomFile>dependencies/umlet-elements/umlet-elements-15.1.pom</pomFile>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>   <!-- three plugins below to generate documentation (javadoc via mvn javadoc:javadoc) -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>4.0.0-M4</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.4.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.11.2</version>
                    <configuration>
                        <author>true</author>
                        <version>true</version>
                        <failOnError>false</failOnError>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
