package cz.cuni.mff.umlift.core.pom;

import org.apache.maven.model.*;
import org.apache.maven.model.io.xpp3.MavenXpp3Writer;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Collections;
import java.util.Properties;
import java.util.logging.Logger;

/**
 * Generates Maven POM for a project generated by {@link cz.cuni.mff.umlift.core.emf.ModelToCodeGenerator}.
 *
 * @since 1.0
 */
public class PomGenerator {
    private static final Logger LOG = Logger.getLogger(PomGenerator.class.getName());
    private final PomConfiguration config;

    private String mavenCompilerPluginVersion = "3.14.0";

    public PomGenerator(PomConfiguration config) {
        this.config = config;
    }

    public Model createPom() {
        Model model = new Model();
        setUpModel(model);
        setUpModelProperties(model);
        addCompilerPlugin(model);
        addDependency(model, "org.eclipse.emf", "org.eclipse.emf.ecore", "2.38.0");

        return model;
    }

    public void savePom(Model model, File outputFile) throws IOException {
        saveModel(model, outputFile);
    }

    public String getMavenCompilerPluginVersion() {
        return mavenCompilerPluginVersion;
    }

    public void setMavenCompilerPluginVersion(String mavenCompilerPluginVersion) {
        this.mavenCompilerPluginVersion = mavenCompilerPluginVersion;
    }

    public Model addDependency(Model model, String groupId, String artifactId, String version) {
        Dependency dependency = new Dependency();
        dependency.setGroupId(groupId);
        dependency.setArtifactId(artifactId);
        dependency.setVersion(version);
        model.addDependency(dependency);
        return model;
    }

    public Model addDependency(Model model, Dependency dependency) {
        model.addDependency(dependency);
        return model;
    }

    public Model addPlugin(Model model, String groupId, String artifactId, String version) {
        Plugin plugin = new Plugin();
        plugin.setGroupId(groupId);
        plugin.setArtifactId(artifactId);
        plugin.setVersion(version);

        model.getBuild().addPlugin(plugin);

        return model;
    }

    public Model addPlugin(Model model, Plugin plugin) {
        model.getBuild().addPlugin(plugin);
        return model;
    }

    public Model addProperty(Model model, String key, String value) {
        model.getProperties().put(key, value);
        return model;
    }

    private void setUpModel(Model model) {
        model.setModelVersion(config.modelVersion());
        model.setGroupId(config.groupId());
        model.setArtifactId(config.artifactId());
        model.setVersion(config.version());
        model.setPackaging(config.packaging().getValue());

    }

    private void setUpModelProperties(Model model) {
        Properties properties = new Properties();
        properties.setProperty("project.build.sourceEncoding", "UTF-8");
        properties.setProperty("maven.compiler.release", config.genJDKLevel().getLiteral().split("\\.")[0]);
        model.setProperties(properties);
    }

    private void addCompilerPlugin(Model model) {
        Plugin plugin = new Plugin();
        plugin.setGroupId("org.apache.maven.plugins");
        plugin.setArtifactId("maven-compiler-plugin");
        plugin.setVersion(mavenCompilerPluginVersion);

        PluginExecution execution = new PluginExecution();
        execution.setPhase("compile");
        execution.setGoals(Collections.singletonList("compile"));
        plugin.setExecutions(Collections.singletonList(execution));

        Build build = new Build();
        build.setPlugins(Collections.singletonList(plugin));
        model.setBuild(build);
    }

    private void saveModel(Model model, File outputFile) throws IOException {
        try (FileWriter writer = new FileWriter(outputFile)) {
            new MavenXpp3Writer().write(writer, model);
            LOG.info("POM generated at " + outputFile.getAbsolutePath());
        }
    }
}
