package cz.cuni.mff.umlift.core.pom;

import cz.cuni.mff.umlift.core.config.GenerationConfig;
import org.apache.maven.model.*;
import org.apache.maven.model.io.xpp3.MavenXpp3Writer;
import org.codehaus.plexus.util.xml.Xpp3Dom;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Collections;
import java.util.Properties;
import java.util.logging.Logger;

/**
 * Generates Maven POM for a project generated by {@link cz.cuni.mff.umlift.core.emf.ModelToCodeGenerator}.
 *
 * @since 1.0
 */
public class PomGenerator {
    private static final Logger LOG = Logger.getLogger(PomGenerator.class.getName());
    private final PomConfiguration pomConfig;
    private final GenerationConfig generationConfig = GenerationConfig.getInstance();

    private String mavenCompilerPluginVersion = "3.14.0";

    public PomGenerator(PomConfiguration pomConfig) {
        this.pomConfig = pomConfig;
    }

    public Model createPom() {
        Model model = new Model();
        setUpModel(model);
        setUpModelProperties(model);
        addDependency(model, "org.eclipse.emf", "org.eclipse.emf.ecore", "2.38.0");

        // Create Plugins
        Plugin compilerPlugin = getCompilerPlugin();

        Build build = new Build();
        build.setPlugins(Collections.singletonList(compilerPlugin));
        model.setBuild(build);

        return model;
    }

    public void savePom(Model model, File outputFile) throws IOException {
        saveModel(model, outputFile);
    }

    public void createAndSavePom(File outputFile) throws IOException {
        savePom(createPom(), outputFile);
    }

    public String getMavenCompilerPluginVersion() {
        return mavenCompilerPluginVersion;
    }

    public void setMavenCompilerPluginVersion(String mavenCompilerPluginVersion) {
        this.mavenCompilerPluginVersion = mavenCompilerPluginVersion;
    }

    public Model addDependency(Model model, String groupId, String artifactId, String version) {
        Dependency dependency = new Dependency();
        dependency.setGroupId(groupId);
        dependency.setArtifactId(artifactId);
        dependency.setVersion(version);
        model.addDependency(dependency);
        return model;
    }

    public Model addDependency(Model model, Dependency dependency) {
        model.addDependency(dependency);
        return model;
    }

    public Model addPlugin(Model model, String groupId, String artifactId, String version) {
        Plugin plugin = new Plugin();
        plugin.setGroupId(groupId);
        plugin.setArtifactId(artifactId);
        plugin.setVersion(version);

        model.getBuild().addPlugin(plugin);

        return model;
    }

    public Model addPlugin(Model model, Plugin plugin) {
        model.getBuild().addPlugin(plugin);
        return model;
    }

    public Model addProperty(Model model, String key, String value) {
        model.getProperties().put(key, value);
        return model;
    }

    private Plugin getUMLiftMavenPlugin() {
        Plugin plugin = new Plugin();

        plugin.setGroupId("cz.cuni.mff");
        plugin.setArtifactId("UMLift-maven-plugin");
        plugin.setVersion("1.0-SNAPSHOT");

        PluginExecution emfFromUMLetExecution = getEmfFromUMLetExecution();

        plugin.setExecutions(Collections.singletonList(emfFromUMLetExecution));

        return plugin;
    }

    private PluginExecution getEmfFromUMLetExecution() {
        PluginExecution execution = new PluginExecution();
        execution.setId("emf-from-umlet");
        //execution.setPhase("compile");
        execution.getGoals().add("generate-emf-from-umlet");

        Xpp3Dom configuration = new Xpp3Dom("configuration");

        Xpp3Dom modelDir = new Xpp3Dom("modelDir");
        modelDir.setValue(generationConfig.getEcoreGenModelDir().toString());

        Xpp3Dom umletFile = new Xpp3Dom("umletFile");
        umletFile.setValue(generationConfig.getInputUMLetFile().toString());

        Xpp3Dom projectName = new Xpp3Dom("projectName");
        projectName.setValue(generationConfig.getProjectName());

        Xpp3Dom NsPrefix = new Xpp3Dom("NsPrefix");
        NsPrefix.setValue(generationConfig.getProjectNsPrefix());

        Xpp3Dom NsURI = new Xpp3Dom("NsURI");
        NsURI.setValue(generationConfig.getProjectNsURI());

        Xpp3Dom ecoreFileName = new Xpp3Dom("ecoreFileName");
        ecoreFileName.setValue(generationConfig.getEcoreFileName());

        Xpp3Dom genModelFileName = new Xpp3Dom("genModelFileName");
        genModelFileName.setValue(generationConfig.getGenModelFileName());

        Xpp3Dom basePackage = new Xpp3Dom("basePackage");
        basePackage.setValue(generationConfig.getBasePackage());

        Xpp3Dom genJDKLevel = new Xpp3Dom("genJDKLevel");
        genJDKLevel.setValue(generationConfig.getGenJDKLevel().toString());

        configuration.addChild(modelDir);
        configuration.addChild(umletFile);
        configuration.addChild(projectName);
        configuration.addChild(NsPrefix);
        configuration.addChild(NsURI);
        configuration.addChild(ecoreFileName);
        configuration.addChild(genModelFileName);
        configuration.addChild(basePackage);
        configuration.addChild(genJDKLevel);

        execution.setConfiguration(configuration);
        return execution;
    }

    private void setUpModel(Model model) {
        model.setModelVersion(pomConfig.modelVersion());
        model.setGroupId(pomConfig.groupId());
        model.setArtifactId(pomConfig.artifactId());
        model.setVersion(pomConfig.version());
        model.setPackaging(pomConfig.packaging().getValue());

    }

    private void setUpModelProperties(Model model) {
        Properties properties = new Properties();
        properties.setProperty("project.build.sourceEncoding", "UTF-8");
        properties.setProperty("maven.compiler.release", pomConfig.genJDKLevel().getLiteral().split("\\.")[0]);
        model.setProperties(properties);
    }

    private Plugin getCompilerPlugin() {
        Plugin plugin = new Plugin();
        plugin.setGroupId("org.apache.maven.plugins");
        plugin.setArtifactId("maven-compiler-plugin");
        plugin.setVersion(mavenCompilerPluginVersion);

        PluginExecution execution = new PluginExecution();
        execution.setPhase("compile");
        execution.setGoals(Collections.singletonList("compile"));
        plugin.setExecutions(Collections.singletonList(execution));

        return plugin;
    }

    private void saveModel(Model model, File outputFile) throws IOException {
        try (FileWriter writer = new FileWriter(outputFile)) {
            new MavenXpp3Writer().write(writer, model);
            LOG.info("POM generated at " + outputFile.getAbsolutePath());
        }
    }
}
