package cz.cuni.mff.umlift.core.pom;

import cz.cuni.mff.umlift.core.config.GenerationConfig;
import org.apache.maven.model.*;
import org.apache.maven.model.io.xpp3.MavenXpp3Writer;
import org.codehaus.plexus.util.xml.Xpp3Dom;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Collections;
import java.util.Properties;
import java.util.logging.Logger;

/**
 * Generates Maven POM for a project generated by {@link cz.cuni.mff.umlift.core.emf.ModelToCodeGenerator}.
 *
 * @since 1.0
 */
public class PomGenerator {
    private static final Logger LOG = Logger.getLogger(PomGenerator.class.getName());
    private final PomConfiguration pomConfig;
    private final GenerationConfig generationConfig = GenerationConfig.getInstance();

    private String mavenCompilerPluginVersion = "3.14.0";

    public PomGenerator(PomConfiguration pomConfig) {
        this.pomConfig = pomConfig;
    }

    /**
     * Creates a Maven POM (Project Object Model) represented by an instance of the {@code Model} class.
     * The generated POM includes basic project metadata, properties, dependencies, and build plugins.
     * <p>
     * The method initializes the model with values from the configuration, sets project properties,
     * adds required dependencies, and configures the Maven compiler plugin for compilation.
     *
     * @return a fully configured {@code Model} instance representing a Maven POM.
     */
    public Model createPom() {
        Model model = new Model();
        setUpModel(model);
        setUpModelProperties(model);
        addDependency(model, "org.eclipse.emf", "org.eclipse.emf.ecore", "2.38.0");

        // Create Plugins
        Plugin compilerPlugin = getCompilerPlugin();

        Build build = new Build();
        build.setPlugins(Collections.singletonList(compilerPlugin));
        model.setBuild(build);

        return model;
    }

    /**
     * Saves the provided Maven {@code Model} to the specified output file.
     * <p>
     * This method writes the structure of the Maven Project Object Model (POM) into the given file
     * using the {@link MavenXpp3Writer}. It ensures that the POM
     * is correctly serialized and outputs the file in the appropriate format.
     *
     * @param model      the Maven {@code Model} instance representing the POM structure to be saved
     * @param outputFile the output {@code File} where the POM model will be saved
     * @throws IOException if an I/O error occurs during writing to the file
     */
    public void savePom(Model model, File outputFile) throws IOException {
        saveModel(model, outputFile);
    }

    /**
     * Generates a Maven POM (Project Object Model) using the current configuration
     * and saves it as a file at the specified location.
     * <p>
     * This method combines the functionality of creating a fully configured Maven
     * {@code Model} with {@link #createPom()} and saving it to the file system using
     * {@link #savePom(Model, File)}. The resulting POM includes project metadata,
     * dependencies, properties, and build plugin configurations as specified by the configuration.
     *
     * @param outputFile the {@code File} location where the generated POM will be saved
     * @throws IOException if an error occurs during POM creation or saving to the specified file
     */
    public void createAndSavePom(File outputFile) throws IOException {
        savePom(createPom(), outputFile);
    }

    public String getMavenCompilerPluginVersion() {
        return mavenCompilerPluginVersion;
    }

    public void setMavenCompilerPluginVersion(String mavenCompilerPluginVersion) {
        this.mavenCompilerPluginVersion = mavenCompilerPluginVersion;
    }

    /**
     * Adds a dependency to the provided Maven {@code Model} instance.
     * This method creates a new {@code Dependency} with the specified
     * group ID, artifact ID, and version, and adds it to the model's
     * list of dependencies.
     *
     * @param model      the Maven {@code Model} to which the dependency will be added
     * @param groupId    the group ID of the dependency
     * @param artifactId the artifact ID of the dependency
     * @param version    the version of the dependency
     * @return the updated Maven {@code Model} instance with the new dependency added
     */
    public Model addDependency(Model model, String groupId, String artifactId, String version) {
        Dependency dependency = new Dependency();
        dependency.setGroupId(groupId);
        dependency.setArtifactId(artifactId);
        dependency.setVersion(version);
        model.addDependency(dependency);
        return model;
    }

    /**
     * Adds a dependency to the provided Maven {@code Model} instance.
     * <p>
     * This method appends the specified {@code Dependency} object
     * to the model's list of dependencies and returns the updated model.
     *
     * @param model      the Maven {@code Model} to which the dependency will be added
     * @param dependency the {@code Dependency} instance to be added to the model
     * @return the updated Maven {@code Model} instance with the new dependency added
     */
    public Model addDependency(Model model, Dependency dependency) {
        model.addDependency(dependency);
        return model;
    }

    /**
     * Adds a plugin to the build section of the provided Maven {@code Model} instance.
     * This method creates a new {@code Plugin} with the specified group ID, artifact ID,
     * and version, and appends it to the model's plugin list.
     *
     * @param model      the Maven {@code Model} to which the plugin will be added
     * @param groupId    the group ID of the plugin
     * @param artifactId the artifact ID of the plugin
     * @param version    the version of the plugin
     * @return the updated Maven {@code Model} instance with the new plugin added
     */
    public Model addPlugin(Model model, String groupId, String artifactId, String version) {
        Plugin plugin = new Plugin();
        plugin.setGroupId(groupId);
        plugin.setArtifactId(artifactId);
        plugin.setVersion(version);

        model.getBuild().addPlugin(plugin);

        return model;
    }

    /**
     * Adds a plugin to the build section of the provided Maven {@code Model} instance.
     * This method appends the specified {@code Plugin} object to the model's plugin list
     * and returns the updated model.
     *
     * @param model  the Maven {@code Model} to which the plugin will be added
     * @param plugin the {@code Plugin} instance to be added to the model
     * @return the updated Maven {@code Model} instance with the new plugin added
     */
    public Model addPlugin(Model model, Plugin plugin) {
        model.getBuild().addPlugin(plugin);
        return model;
    }

    /**
     * Adds a property to the properties section of the provided Maven {@code Model} instance.
     * The key and value are added as a key-value pair to the model's properties map.
     *
     * @param model the Maven {@code Model} to which the property will be added
     * @param key   the property key to be added to the model
     * @param value the property value to be associated with the specified key
     * @return the updated Maven {@code Model} instance with the new property added
     */
    public Model addProperty(Model model, String key, String value) {
        model.getProperties().put(key, value);
        return model;
    }

    /**
     * Creates and configures the UMLift Maven plugin instance.
     * This method sets the group ID, artifact ID, version of the plugin,
     * and associates a plugin execution configuration for generating EMF
     * models from UMLet files.
     *
     * @return a {@code Plugin} instance representing the configured UMLift Maven plugin
     */
    private Plugin getUMLiftMavenPlugin() {
        Plugin plugin = new Plugin();

        plugin.setGroupId("cz.cuni.mff");
        plugin.setArtifactId("UMLift-maven-plugin");
        plugin.setVersion("1.0-SNAPSHOT");

        PluginExecution emfFromUMLetExecution = getEmfFromUMLetExecution();

        plugin.setExecutions(Collections.singletonList(emfFromUMLetExecution));

        return plugin;
    }

    /**
     * Creates and configures a {@code PluginExecution} instance for generating EMF (Eclipse Modeling Framework)
     * models based on UMLet diagrams. The method defines the unique execution ID, the goal to be executed,
     * and the necessary configuration parameters required for the execution.
     * <p>
     * The configuration includes details such as the source UMLet file, output directory for the generated
     * models, project metadata, and other settings to ensure proper generation of the EMF models.
     *
     * @return a fully configured {@code PluginExecution} instance for EMF model generation from UMLet.
     */
    private PluginExecution getEmfFromUMLetExecution() {
        PluginExecution execution = new PluginExecution();
        execution.setId("emf-from-umlet");
        //execution.setPhase("compile");
        execution.getGoals().add("generate-emf-from-umlet");

        Xpp3Dom configuration = new Xpp3Dom("configuration");

        Xpp3Dom modelDir = new Xpp3Dom("modelDir");
        modelDir.setValue(generationConfig.getEcoreGenModelDir().toString());

        Xpp3Dom umletFile = new Xpp3Dom("umletFile");
        umletFile.setValue(generationConfig.getInputUMLetFile().toString());

        Xpp3Dom projectName = new Xpp3Dom("projectName");
        projectName.setValue(generationConfig.getProjectName());

        Xpp3Dom NsPrefix = new Xpp3Dom("NsPrefix");
        NsPrefix.setValue(generationConfig.getProjectNsPrefix());

        Xpp3Dom NsURI = new Xpp3Dom("NsURI");
        NsURI.setValue(generationConfig.getProjectNsURI());

        Xpp3Dom ecoreFileName = new Xpp3Dom("ecoreFileName");
        ecoreFileName.setValue(generationConfig.getEcoreFileName());

        Xpp3Dom genModelFileName = new Xpp3Dom("genModelFileName");
        genModelFileName.setValue(generationConfig.getGenModelFileName());

        Xpp3Dom basePackage = new Xpp3Dom("basePackage");
        basePackage.setValue(generationConfig.getBasePackage());

        Xpp3Dom genJDKLevel = new Xpp3Dom("genJDKLevel");
        genJDKLevel.setValue(generationConfig.getGenJDKLevel().toString());

        configuration.addChild(modelDir);
        configuration.addChild(umletFile);
        configuration.addChild(projectName);
        configuration.addChild(NsPrefix);
        configuration.addChild(NsURI);
        configuration.addChild(ecoreFileName);
        configuration.addChild(genModelFileName);
        configuration.addChild(basePackage);
        configuration.addChild(genJDKLevel);

        execution.setConfiguration(configuration);
        return execution;
    }

    /**
     * Configures the provided Maven {@code Model} instance with essential project metadata.
     * This method initializes the model's version, group ID, artifact ID, version, and packaging type
     * based on the values obtained from the {@code PomConfiguration}.
     *
     * @param model the Maven {@code Model} instance to be configured
     */
    private void setUpModel(Model model) {
        model.setModelVersion(pomConfig.modelVersion());
        model.setGroupId(pomConfig.groupId());
        model.setArtifactId(pomConfig.artifactId());
        model.setVersion(pomConfig.version());
        model.setPackaging(pomConfig.packaging().getValue());

    }

    /**
     * Configures the properties of the provided Maven {@code Model} instance.
     * This method initializes the model's properties section with key-value pairs
     * that specify project parameters such as source encoding and JDK level.
     *
     * @param model the Maven {@code Model} instance whose properties will be configured
     */
    private void setUpModelProperties(Model model) {
        Properties properties = new Properties();
        properties.setProperty("project.build.sourceEncoding", "UTF-8");
        properties.setProperty("maven.compiler.release", pomConfig.genJDKLevel().getLiteral().split("\\.")[0]);
        model.setProperties(properties);
    }

    /**
     * Creates and configures a {@code Plugin} instance representing the Maven Compiler Plugin.
     * This method initializes the plugin with its group ID, artifact ID, and version, and sets up
     * a plugin execution for the "compile" phase with the "compile" goal.
     *
     * @return a fully configured {@code Plugin} instance representing the Maven Compiler Plugin.
     */
    private Plugin getCompilerPlugin() {
        Plugin plugin = new Plugin();
        plugin.setGroupId("org.apache.maven.plugins");
        plugin.setArtifactId("maven-compiler-plugin");
        plugin.setVersion(mavenCompilerPluginVersion);

        PluginExecution execution = new PluginExecution();
        execution.setPhase("compile");
        execution.setGoals(Collections.singletonList("compile"));
        plugin.setExecutions(Collections.singletonList(execution));

        return plugin;
    }

    /**
     * Saves the provided Maven {@code Model} instance to the specified file.
     * <p>
     * This method serializes the Maven Project Object Model (POM) represented by the
     * {@code Model} instance and writes it to the given output file. It uses the
     * {@code MavenXpp3Writer} to ensure that the POM is formatted and saved correctly.
     *
     * @param model      the Maven {@code Model} instance representing the POM structure to be saved
     * @param outputFile the output {@code File} where the POM model will be saved
     * @throws IOException if an I/O error occurs while writing the file
     */
    private void saveModel(Model model, File outputFile) throws IOException {
        try (FileWriter writer = new FileWriter(outputFile)) {
            new MavenXpp3Writer().write(writer, model);
            LOG.info("POM generated at " + outputFile.getAbsolutePath());
        }
    }
}
