<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cz.cuni.mff.vojtusr</groupId>
        <artifactId>Eclipse-plugin</artifactId>
        <version>1.0.6</version>
    </parent>

    <artifactId>InformalMDD-update-site</artifactId>
    <version>1.0.6</version>
    <packaging>eclipse-repository</packaging>

    <dependencies>
        <dependency>
            <groupId>cz.cuni.mff.vojtusr</groupId>
            <artifactId>InformalMDD-feature</artifactId>
            <version>1.0.6</version>
            <type>eclipse-feature</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>4.0.9</version>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>p2-repo</id>
            <layout>p2</layout>
            <url>https://download.eclipse.org/releases/latest/</url>
        </repository>
    </repositories>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>