<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exampleProject" nsURI="https://example.org/exampleProject" nsPrefix="exampleProjectPrefix">
  <eClassifiers xsi:type="ecore:EClass" name="Web" eSuperTypes="//SuperClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="webpage" upperBound="2" eType="//Webpage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnumName" eType="//EnumName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Webpage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Category" upperBound="-1" eType="//Category" eOpposite="//Category/Webpage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass" eSuperTypes="//InterfaceName"/>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Webpage" eType="//Webpage" eOpposite="//Webpage/Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Article" lowerBound="1" upperBound="3" eType="//Article" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceName" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumName"/>
</ecore:EPackage>
